-- JP Control web admin database schema
-- Run this once in Supabase SQL Editor for the project used by the website.

create table if not exists public.statistics (
  id integer primary key default 1,
  performed_inspections integer not null default 15000 check (performed_inspections >= 0),
  years_experience_start integer not null default 2014 check (years_experience_start between 1900 and 2100),
  satisfaction_percentage numeric not null default 98 check (satisfaction_percentage >= 0 and satisfaction_percentage <= 100),
  google_place_id text,
  updated_at timestamptz not null default now()
);

insert into public.statistics (
  id,
  performed_inspections,
  years_experience_start,
  satisfaction_percentage,
  google_place_id,
  updated_at
) values (
  1,
  15000,
  2014,
  98,
  null,
  now()
) on conflict (id) do nothing;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  text text not null,
  background_color text,
  background_gradient text,
  border_color text,
  text_color text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  link text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  text text not null,
  rating integer not null default 5 check (rating between 1 and 5),
  approved boolean not null default false,
  source text not null default 'manual',
  relative_time_description text not null default 'nedávno',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notifications_active_created_idx
  on public.notifications (active, created_at desc);

create index if not exists partners_active_sort_idx
  on public.partners (active, sort_order, created_at);

create index if not exists reviews_approved_created_idx
  on public.reviews (approved, created_at desc);

alter table public.statistics enable row level security;
alter table public.notifications enable row level security;
alter table public.partners enable row level security;
alter table public.reviews enable row level security;

-- The website API uses SUPABASE_SERVICE_ROLE_KEY on the server, which bypasses RLS.
-- No public table policies are needed.

insert into storage.buckets (id, name, public)
values ('partners', 'partners', true)
on conflict (id) do update set public = excluded.public;
